name: Changes in the catalog

on:
  pull_request:
    branches: 
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged && contains( github.event.pull_request.labels.*.name, 'catalog') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Generate plot
        run: |
          python -c 'import lenscat; from lenscat.utils import plot_catalog; plot_catalog(lenscat.catalog)'
      - name: Change _version.py file
        run : |
          python -c "import lenscat._version; vers=lenscat._version.__version__.split('.');vers[-1]=str(int(vers[-1])+1);f=open('lenscat/_version.py', 'w');f.write(\"__version__ = '\"+'.'.join(vers)+\"'\");f.close()"
          echo "VERSTR=$(python -c 'import lenscat._version;print(lenscat._version.__version__)')" >> $GITHUB_ENV
      - name: Update README.md
        continue-on-error: true # Allow failure
        run : |
          pip install ipython
          bash .github/workflows/update_README.sh
      - name: Configure git user info
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Upload plot to repository
        continue-on-error: true # Allow failure
        run: |
          git add catalog.png
          git commit -m "Re-generate catalog plot"
          git push
      - name: Upload README to repository
        continue-on-error: true # Allow failure
        run: |
          git add README.md
          git commit -m "Update README.md"
          git push
      - name: Bump version
        run: |
          git add lenscat/_version.py
          git commit -m "Bump to v${{ env.VERSTR }}"
          git push
