name: Create Release and Tag

on:
  workflow_run:
    workflows: ["Changes in the catalog"]
    types:
      - completed

permissions: write-all

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: pypi
      url: https://pypi.org/p/lenscat
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Get version string
        run: |
          echo "VERSTR=$(python -c 'exec(open('\''lenscat/_version.py'\'').read()); print(__version__)')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSTR }}
          release_name: ${{ env.VERSTR }}
          body: |
            Changes in the catalog
          draft: false
          prerelease: false
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
