name: Plot catalog

on:
  pull_request:
    branches: 
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  plot_catalog:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Generate plot
        run: |
          python -c 'import lenscat; from lenscat.utils import plot_catalog; plot_catalog(lenscat.catalog)'
      - name: Upload plot to repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add catalog.png
          git commit -m "Re-generate catalog plot"
          git push
